"""block user

Revision ID: 70526b84e1be
Revises: 3b2e526c1a21
Create Date: 2025-07-17 14:12:59.577366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70526b84e1be'
down_revision = '3b2e526c1a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blocked')

    # ### end Alembic commands ###
